

const profileTypes = {

  FETCH_PROFILE_START: "FETCH_PROFILE_START",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_ERROR: "FETCH_PROFILE_ERROR",

  FETCH_ADDITIONAL_POSTS_START: "FETCH_ADDITIONAL_POSTS_START",
  FETCH_ADDITIONAL_POSTS_SUCCESS: "FETCH_ADDITIONAL_POSTS_SUCCESS",
  FETCH_ADDITIONAL_POSTS_ERROR: "FETCH_ADDITIONAL_POSTS_ERROR",

  SET_POST_VOTES_COUNT: "SET_POST_VOTES_COUNT",
  INCREMENT_POST_COMMENTS_COUNT: "INCREMENT_POST_COMMENTS_COUNT",
  DECREMENT_POST_COMMENTS_COUNT: "DECREMENT_POST_COMMENTS_COUNT",

  ADD_POSTS: "ADD_POSTS",
  DELETE_POST: "DELETE_POST",

  FOLLOW_USER_START: "FOLLOW_USER_START",
  FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
  FOLLOW_USER_ERROR: "FOLLOW_USER_ERROR"

};

export default profileTypes;
