const chatTypes = {

  FETCH_CONVERSATIONS_START: "FETCH_CONVERSATIONS_START",
  FETCH_CONVERSATIONS_SUCCESS: "FETCH_CONVERSATIONS_SUCCESS",
  FETCH_CONVERSATIONS_ERROR: "FETCH_CONVERSATIONS_ERROR",

  FETCH_MESSAGES_START: "FETCH_MESSAGES_START",
  FETCH_MESSAGES_SUCCESS: "FETCH_MESSAGES_SUCCESS",
  FETCH_MESSAGES_ERROR: "FETCH_MESSAGES_ERROR",
  //socket.io
  SEND_MESSAGE_START: "SEND_MESSAGE_START",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_ERROR: "SEND_MESSAGE_ERROR",

  RECEIVE_MESSAGE_START: "RECEIVE_MESSAGE_START",
  RECEIVE_MESSAGE_SUCCESS: "RECEIVE_MESSAGE_SUCCESS",
  RECEIVE_MESSAGE_ERROR: "RECEIVE_MESSAGE_ERROR",

  READ_MESSAGE_START: "READ_MESSAGE_START",
  READ_MESSAGE_SUCCESS: "READ_MESSAGE_SUCCESS",
  READ_MESSAGE_ERROR: "READ_MESSAGE_ERROR",
};

export default chatTypes;
