const chatTypes = {
  SEND_MESSAGE_STARTED: "SEND_MESSAGE_STARTED",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_ERROR: "SEND_MESSAGE_ERROR",
  FETCH_CONVERSATIONS_STARTED: "FETCH_CONVERSATIONS_STARTED",
  FETCH_CONVERSATIONS_SUCCESS: "FETCH_CONVERSATIONS_SUCCESS",
  FETCH_CONVERSATIONS_ERROR: "FETCH_CONVERSATIONS_ERROR",
  NEW_MESSAGE_RECEIVED: "NEW_MESSAGE_RECEIVED",
};

export default chatTypes;
