const userTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  GITHUB_SIGN_IN_START: "GITHUB_SIGN_IN_START",
  GITHUB_SIGN_IN_FAILURE: "GITHUB_SIGN_IN_FAILURE",
  GITHUB_SIGN_IN_SUCCESS: "GITHUB_SIGN_IN_SUCCESS",

  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  GOOGLE_SIGN_IN_FAILURE: "GOOGLE_SIGN_IN_FAILURE",
  GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",

  FACEBOOK_SIGN_IN_START: "FACEBOOK_SIGN_IN_START",
  FACEBOOK_SIGN_IN_FAILURE: "FACEBOOK_SIGN_IN_FAILURE",
  FACEBOOK_SIGN_IN_SUCCESS: "FACEBOOK_SIGN_IN_SUCCESS",

  TWITTER_SIGN_IN_START: "TWITTER_SIGN_IN_START",
  TWITTER_SIGN_IN_FAILURE: "TWITTER_SIGN_IN_FAILURE",
  TWITTER_SIGN_IN_SUCCESS: "TWITTER_SIGN_IN_SUCCESS",

  BOOKMARK_POST: "BOOKMARK_POST",
  CHANGE_AVATAR_START: "CHANGE_AVATAR_START",
  CHANGE_AVATAR_SUCCESS: "CHANGE_AVATAR_SUCCESS",
  CHANGE_AVATAR_FAILURE: "CHANGE_AVATAR_FAILURE",
  REMOVE_AVATAR_START: "REMOVE_AVATAR_START",
  REMOVE_AVATAR_SUCCESS: "REMOVE_AVATAR_SUCCESS",
  REMOVE_AVATAR_FAILURE: "REMOVE_AVATAR_FAILURE",

  CHANGE_COVER_PICTURE_START: "CHANGE_COVER_PICTURE_START",
  CHANGE_COVER_PICTURE_SUCCESS: "CHANGE_COVER_PICTURE_SUCCESS",
  CHANGE_COVER_PICTURE_FAILURE: "CHANGE_COVER_PICTURE_FAILURE",
  REMOVE_COVER_PICTURE_START: "REMOVE_COVER_PICTURE_START",
  REMOVE_COVER_PICTURE_SUCCESS: "REMOVE_COVER_PICTURE_SUCCESS",
  REMOVE_COVER_PICTURE_FAILURE: "REMOVE_COVER_PICTURE_FAILURE",

  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",

  UPDATE_CREATOR_START: "UPDATE_CREATOR_START",
  UPDATE_CREATOR_FAILURE: "UPDATE_CREATOR_FAILURE",
  UPDATE_CREATOR_SUCCESS: "UPDATE_CREATOR_SUCCESS",

  SEND_TIP_START: "SEND_TIP_START",
  SEND_TIP_FAILURE: "SEND_TIP_FAILURE",
  SEND_TIP_SUCCESS: "SEND_TIP_SUCCESS",

  FETCH_PROFILE_START: "FETCH_PROFILE_START",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",


  //socket.io
  UPDATE_MESSAGE_PRICE_START: "UPDATE_MESSAGE_PRICE_START",
  UPDATE_MESSAGE_PRICE_SUCCESS: "UPDATE_MESSAGE_PRICE_SUCCESS",
  UPDATE_MESSAGE_PRICE_ERROR: "UPDATE_MESSAGE_PRICE_ERROR",


  UPDATE_BALANCE_SUCCESS: "UPDATE_BALANCE_SUCCESS",

  PARTICIPANT_PEER_ID_UPDATED: "PARTICIPANT_PEER_ID_UPDATED",

};

export default userTypes;
